### ISSUE TITLE
Problem during the installation

### ISSUE THREAD

**Issue by ipa-vsp** [pieye/nimbus-userland#1]
Hi

I have followed the given [Installation](https://github.com/pieye/nimbus-userland#installation) steps and also activated the ssh `sudo raspi-config`. After the reboot, I was not able to stream the video because of the following reason. 
![20191118_160630](https://user-images.githubusercontent.com/32260301/69064390-68193300-0a1e-11ea-90a2-8c72395134dc.jpg)
Is there anything I am missing? 

Thank you 

Best Regards
Vishnu

**Comment by Coimbra1984** [comment]
Hi Vishnu,

1. did you reboot the device?
2. can you give the output of `dmesg | grep irs1125` please
3. please give the content of file /tmp/nimbus_server_*** if exists

Best regards,

Markus

**Comment by ipa-vsp** [comment]
Hi,
1. Yes, I have rebooted the raspi.
2. `dmesg | grep irs1125` for this command there is no output!
3. The data on the log file as follows.
```
GNU nano 3.2    /tmp/nimbus_server_log.g3log.20191118-161703.log    Modified

              g3log created log at: Mon Nov 18 16:17:03 2019
                LOG format: [YYYY/MM/DD hh:mm:ss uuu* LEVEL FILE->FUNCTION:LINE$
                (uuu*: microseconds fractions of the seconds value)

2019/11/18 16:17:03 291734      INFO [main.cpp->main:123]       creating prepro$
2019/11/18 16:17:03 292007      WARNING [tmp102.cpp->Tmp102:62] error opening i$
2019/11/18 16:17:03 292054      WARNING [tmp102.cpp->Tmp102:69] error opening i$
2019/11/18 16:17:03 292073      WARNING [tmp102.cpp->Tmp102:77] error setting p$
2019/11/18 16:17:03 293318      WARNING [nimbusRaw.cpp->setNumSequences:765]   $
2019/11/18 16:17:03 294077      FATAL [nimbusRaw.cpp->initV4L2Buffers:439]
        *******  EXIT trigger caused by LOG(FATAL) entry:
        "/dev/video10 is no video capture device
******* STACKDUMP *******

        stack dump [1]  /usr/local/lib/libg3logger.so.1.3.2-80 : LogCapture::Lo$

        stack dump [2]  /usr/local/lib/libnimbus-preprocessing.so : nimbus::Nim$

$s::Nim$                g3log created log at: Mon Nov 18 16:17:03 2019
```

**Comment by Coimbra1984** [comment]
> dmesg | grep irs1125 for this command there is no output!

Okay this means, that your camera is probably not properly connected to the system.
1. Can you check the correct mounting of the FCC connector
2. Can you check that you connected it correctly to the pinheader.

See the usermanual at https://cloud.pieye.org/index.php/s/c2QSa6P4wBtSJ4K for details about correct mounting.
If it is mounted correctly, can you verify that you added dtoverlay=irs1125 to /boot/config.txt and give the output of `uname -a`
