### ISSUE TITLE
nimbus library and nimbus server source code

### ISSUE THREAD

**Issue by ravijj** [pieye/nimbus-userland#2]
Dear nimbus team,

I am currently working on the IRS1125A Nimbus camera sensor module with Raspberry Pi board setup.
I have verified the camera stream over the web access and  it worked fine.

I was wondering, where i can find the nimbus server and nimbus library (libnimbus-preprocessing, libnimbus-eeprom etc) source code for study?

Thanks and Regards,
Ravikiran J J

**Comment by Coimbra1984** [comment]
Hi,

these libraries are closed source, you won't find them.

Best regards

**Comment by ravijj** [comment]
Hi,

Thank you for the information.

We are planning to integrate the IRS1125A Nimbus Camera module with Qualcomm QCM2290 Soc platform board.
Do you have any inputs regarding the libraries support for 3D data processing(Amplitude, Radial, X,Y, Z and Conf) from the RAW image data capturing from the IRS1125A Nimbus Camera sensor module?

Your help in this matter is highly appreciated.

Thanks and Regards,
Ravikiran J J
